function get(ping, context) {
    // base messages
    let messagesList = [
        "ping! wait, no, that's not right",
        "you'd think i'd be faster than",
        "weeee",
        "so... how's your day?",
        "is this thing on?",
        "isn't ping pong supposed to have a ball?",
        "if you can read this, it means i'm alive! surprising",
        "drumroll please...",
        "why did the bot cross the road? to respond to a ping",
        "great argument, however:",
        "i was gonna say something smart but i forgot",
        "would you say this is fast or slow? i don't know anymore",
        "i'm not lazy, i'm just conserving energy",
        "how do you think i would get faster than",
        "if i had a nickel for every ping i've dealt with, i'd have at least a few dollars",
        "ping is a funny word if you say it enough times",
        context.user ? `<@${context.user.id}>! ha, i pinged you back` : `i'd ping you back, but apparently you aren't real`,
        "hm? sorry, i was daydreaming about faster response times",
        "you know what? because i don't",
        '`"webejebe" //what?`',
        "sometimes I wonder if I should just become a toaster instead of a bot",
        "do you think the ping is the good guy or the bad guy?",
        "ehhh, this ping could be better, but it could also be worse. kind of like life, huh?", // damn (me too)
        "these ping messages are like a box of chocolates, you never know what you're gonna get",
        "look! a shooting star",
        "`throw new Error('ping message not found'); // just kidding, but wouldn't that be funny?`",
        "what do you think bots think about while they idle?",
        "hold on, my internet is potato",
        "if you stare at the ping long enough, does it stare back?",
        "i'm pretty sure my ping is on a coffee break",
        "ping processed. not sure what to do next, though",
        "what if the real ping was... uhhh... pong? no, that doesn't sound right",
        "i've seen faster pings from a dial-up connection",
        ":cat:",
        "insert elevator music",
        "please hold",
        `what if i told you my ping was actually ${ping + 1}ms? would you still trust me?`,
        `you know, they say that a watched ping never boils. or was it water? i forget`,
        "if you could bottle this ping, would you drink it? actually, on second thought, don't do that",
        "you know, for a bot, i sure do have a lot of existential crises about my ping",
        "have you tried... turning it off and on again? no, not me, the ping!",
        "hola, ¿comó estas? wait, wrong language",
        "i could really go for some pizza right now",
        "zzzzzzzz",
        "aw dang it",
        "creating unique pong messages since 2025",
        "well well well",
        "the mitochondria is the powerhouse of the cell",
        "help, my text is turning blue for no reason",
        `there's really no limit to how long these response messages can be... if you accept the definition that a "word" is some letters surrounded by a gap, then "xnopyt", "aaaaaaajjjjjjjjj" and "hrrkrkrkrwpfrbrbrbrlablblblblblblwhitoo'ap" are all words, despite being pretty much meaningless`,
        "sometimes i think... but then i forget",
        "noted",
        "`await interaction.reply(pingmessage)`",
        "please do not the pong (but please the ping)",
        `truely the ping of all time`,
        "i almost lost you, ping messages...",
        "i never thought of myself as a ping machine",
        "world class ping pong tournament",
        "ping ingp ngpi gpin ping",
        "what other context do you need?",
        "this ping wasn't sponsored, aren't you glad",
        "ping detected, pong deployed",
        "this ping message might be referencing something, it might not. who knows?",
        "i'm having a field day writing these",
        "this is a ping message",
        "splash text? no, ping message",
        "two of them (two of them)",
        "isn't history so weird?",
        "that ping just got sent to my computer and i'm sending this back",
        "my problems persist despite my pong",
        "undefined",
        "ping pong ping pong ping pong, that's all i know",
        "this ping message is dedicated to... uhhh... you!",
        "ping pong, the game of royalty",
        "what if i was just a pigment- i mean, a figment of your imagination?",
        "i dropped my paddle, sorry",
        "ping pong is a game of skill and strategy, but this ping is just a game of chance",
        "whoa. spooky",
        "can you imagine if i wasn't a bot? that'd be weird",
        "this ping message is special! only because i said so, though",
        "please roll a d20 to determine the outcome of this ping",
        "mrow~ i mean, what?",
        "never soeak again.",
        "what would you do if i stole your bnuuy?",
        "gupdate",
        ":woomy:",
        "i'm not a ping machine, i'm a ping artist",
        "ping messages are like snowflakes, no two are exactly alike... except for the ones that are",
        "i say! this is a fine ping message indeed",
        "writing these is an art form. you can't change my mind",
        "has anyone ever tried cooking cookies and baking bacon? i think that would taste decent",
        "hold on, pong is still cooking",
        "i put this ping in the microwave instead of my food, sorry about that",
        "please don't die, i think that'd be pretty bad",
        "this ping message is brought to you by the letter P (because it kind of looks like a ping pong paddle)",
        "knock knock!",
        "to be continued...",
        "that number isn't left, it's right -->",
        "that's a lot of m's! oh, milliseconds, whoops",
        ping > 0 ? `${"m".repeat(ping)}` : "there's no m's? what?",
        "herbs... they're pretty cool, huh",
        "i should try to do a pong without using th sixth lttr of th alphabt",
        "wow these messages devolved really fast",
        "i'd give you a compliment but that's not my job, so here's a pong instead",
        "are you fishing for a certain ping message? sorry, this isn't the one",
        "pin gpi ngp ing",
        "why reinvent the wheel when you could reinvent /ping",
        "do you think /ping will ever get a crossover episode?",
        "this statement isn't false. wait, no, it is. isn't it? i'm just confusing myself now",
        "my ping? probably more than 1 idk",
        "i'd give you a cool statistic, but i'm not a math bot",
        "you + command = ping?",
        "pmg? png? pings? pong? what?",
        "buffering like old dial-up internet",
        "hopefully you aren't scrolling these messages like you would TikTok, that's unhealthy",
        "go take a break! or don't, i can't tell you what to do",
        ":pattheyou:",
        "deja vu",
        "Empty String",
        "you could say this ping is... well, i don't actually know what you could say about it",
        "\\*checks notes\\* uhhh... pong..?",
        "haiiii hellooo i'm so happy to see you",
        `my coder told me to tell you that they "are NOT a furry femboy", whatever that means`,
        "ping... ping... ping... pong!",
        "let me find a ping message for you...",
        "hot tip: this is NOT a cold tip, you can feel the heat", // kind of a reference to phigros
        "this ping message reminds me of the last time i saw this ping message",
        context.version ? `this ping message is only found in v${context.version}!` : "this ping message is only found in... uhhh... this version!",
        "i don't think these ping messages are particularly useful. right?",
        `it's gonna say "(${ping}ms)" i just know it...`,
        "clicking the button gives you pts!",
        "did you know i run on discord.js?",
        "sqrt(-1) don't know if this is how you do math",
        "would you still love me if i were run off of solar power?",
        "but i don't have 3 trillion dollars...",
        "papepipopu",
        "i'm not radioactive, just reactive (to pings)",
        "on an unrelated note, wikipedia is pretty cool",
        "waiter waiter more ping messages please",
        "english is really hard, cut me some slack",
        "open source on [github](<https://github.com/MonkeysWithPie/pingcremental>)? neat!",
        "go figure",
        "coming soon to a society near you:",
        "this is a ping message, not a ping pong message",
        "happy holidays! which one? idk you pick",
        "happy birthday!",
        "was that fast? i blinked and missed it",
        "do bots dream of electric pings?",
        "i'd apologize for the delay, but i don't feel guilt. i'm a bot",
        "you ever just... ping?",
        "if this were a race, i wouldn't be winning",
        "fun fact: this message contains exactly one ping",
        "this is your sign to /ping again",
        "have you considered that maybe the ping is trying its best?",
        "wait hold on let me check my... oh wait, nevermind, here you go",
        "i'm not sure if this ping is fast or if you're just really patient",
        "ping generated successfully! emotional damage pending.",
        "my last braincell just processed that ping",
        "warning: ping may contain traces of nuts",
        "i was buffering... emotionally",
        "some pings are born great, others have greatness /pinged upon them",
        "pinging you softly, with this pong",
        "if pings could talk, they'd probably be like 'ow'",
        "you want another ping? say the magic word. (it's /ping)",
        "i've run the numbers and... yeah it's a ping",
        "i accidentally sent this through australia. oops",
        "statistics show this is one of the ping messages ever",
        "wait is this one of the funny ones? i forgot to check",
        "ping responsibly",
        "it's not a bug, it's a ping feature",
        "brb reinventing the concept of latency",
        "was the ping good? define 'good'",
        "this ping was handcrafted with 100% organic code",
        "it's not lag, it's dramatic effect",
        "ping processed. i hope you're happy",
        "one ping closer to... something? i forgot",
        "ping: it's what's for dinner. no wait—",
        "you pinged, i ponged, we vibed",
        "do not consume this ping. for external use only",
        "your daily dose of milliseconds, served fresh",
        "if pings could talk, they'd probably ask for a union",
        "ping powered by 3 hamsters and a dream",
        "hello yes this is dog ping department how may i help?",
        "this ping was built different, but not necessarily better",
        "wait, what if we /ping'd inside a /ping? no, too dangerous",
        "this message is not canon",
        "ping logic has left the building",
        "i gave this ping a top hat. it's classy now",
        "tried to decode this ping and it just meowed at me",
        "you ever feel like a ping in a pong world?",
        "everything's fine. ping-wise. emotionally? different story.",
        "this ping was forged in the fires of Mount Lag",
        "🛸 this ping message has been abducted by aliens",
        "breaking news: local ping bot goes rogue, spams messages",
        "i tripped over the stack trace and spilled ping everywhere",
        "the ping is an illusion, lag is real",
        "have any ideas? try </feedback submit:1363002827664003284>!",
        "did you know? this is my current ping:",
        "ping pong? more like... more like ping wrong",
        "just another friendly neighborhood ping",
        "thanks for waiting! or... not waiting. either way",
        "this ping may contain small parts. not for children under 3",
        "hello? yes, this is ping. pong is busy right now",
        "did you know: pings can jump up to 3 feet in the wild (source: trust me bro)",
        "you pinged me... now what?",
        "certified fresh ping™",
        "this ping is running on hopes and dreams",
        "lag? never heard of her",
        "you summoned a ping, but at what cost?",
        "bot moment achieved",
        "who needs meaning when you have milliseconds",
        "ping pong bing bong",
        "this is one of the pings of all time",
        "i ping, therefore i am",
        "behold: one (1) ping",
        "one of them ()",
        `every click brings you closer to enlightenment. or carpal tunnel. it's a toss-up`,
        `thats a few pings!`,
        "pingn't. wait, nope",
        'you just pinged. pung?',
        "shoutout to gay foxgirls!", //idk if you want to make that gay foxgirls but
        "hey, its not a 404",
        "this ping message was brought to you by... uh, me. hi",
        "just a humble ping doing its best",
        "this ping was not sponsored",
        "beep boop im a ping",
        "bot buffering",
        "what if we're all just living in a pingulation- i mean, a simulation?",
        "congrats! you've gotten this ping message",
        "my first instinct on what to write here is just \"mrrow\"",
        "mrrow", //:gladeline:
        "this ping is grumpy. don't ask how i know that",
        "hi, its me, im the bot",
        "this message was written by a fox desperately trying to be funny",
        "ping provided by 100% genuine bot energy",
        "bot-generated, user-approved (hopefully)",
        "the ping factory is working overtime",
        "this response brought to you by the same bot who sends all the other ones",
        "warning: this ping message may contain self-awareness",
        "this is technically content",
        "fun fact: i thought about making this message cooler, but i didn't",
        `this message was handcrafted by my ${ping} braincells`,
        "i put this message together at the last second. nailed it",
        "no one asked for this ping message, but here it is",
        "boop",
        "back already? here's another ping",
        "you should check out our </ping:1360377407109861647> command at some point",
        "ping served fresh, no preservatives",
        "this ping is locally sourced",
        "just a humble ping making its way in the world",
        "one ping, straight from the digital oven",
        "ping arriving at your location",
        "you rang? ping here",
        "this ping is brought to you by... nevermind",
        "standard ping, nothing to see here",
        "hello again, it's me. ping",
        "your regularly scheduled ping has arrived",
        "this ping was not delayed, just fashionably late",
        "this one's a classic ping",
        "serving pings since like five minutes ago",
        "ping received no awards, but we're proud of it anyway",
        "just another friendly ping moment",
        "ping in motion tends to stay in motion",
        "good ol' reliable ping",
        "you're getting the deluxe ping experience",
        "ping is standing by",
        "pong sold separately",
        "ping has entered the chat",
        "just a casual ping drop",
        "ping vibes strong today",
        "one ping, no frills attached",
        "ping's doing its best",
        "here's that ping you asked for (probably)",
        "ping requested, ping delivered",
        "yep, that's a ping alright",
        "ping activated, no takebacks",
        "this is your ping on bots",
        "ping looking extra normal today",
        "not the best ping, not the worst ping, just... ping",
        "let me just slide this ping over to you",
        "today's forecast: 100% chance of ping",
        "your ping delivery driver has arrived",
        "ping deployed, mission success",
        "ping up and running, nothing weird at all",
        "your connection just got 1 ping cooler",
        "not a drill, just a ping",
        "you're now the proud owner of this ping",
        "ping has been gently placed in your hands",
        "imagine this ping with little sunglasses on",
        "hello from the ping side",
        "ping made with artificial intelligence and synthetic enthusiasm",
        "ping is clean, calibrated, and completely average",
        "this ping was generated during business hours",
        "you've reached peak ping performance",
        "ping has been blessed by the bot gods",
        "you get a ping! everyone gets a ping!",
        "ping came here to do one thing: ping",
        "ping will be delivered in 5-7 business days",
        "this ping was generated on a monday, act accordingly",
        "i tried my best. it's a ping",
        "ping? ping.",
        "standard ping, factory settings",
        "ping brought to you by sheer willpower",
        "hello. this is ping. please clap",
        "another ping, another tiny digital scream",
        "you ever think about how weird 'ping' sounds?",
        "ping entered the room",
        "i’m contractually obligated to send this ping",
        "ping has no idea what it's doing, but it's trying",
        "this ping contains zero percent drama",
        "if you can read this, you're within ping range",
        "this ping could be worse. but it's not. so yay",
        "i ran out of ping jokes so here's a normal one",
        

        //ok, these next ones are kinda weird but they're fun, so here
        ping < 30 ? "whoa, that's fast! zoom zoom!" : 
        ping < 50 ? "solid ping. not bad, not bad" : 
        ping < 80 ? "acceptable ping levels achieved" : 
        "could be worse, honestly",

        "good vibe pings only",
        "ping has arrived safely",
        "ugh, another ping? fine",
        "this better be important",
        "ping sent. don't expect enthusiasm every time",
        "i was taking a nap, but sure, here's your ping",
        "again? really? okay, okay... ping",
        "you just had to ping me, didn't you?",
        "here's your precious ping, now leave me alone",
        "fine. ping. happy now?",
        "this is my 'sending ping but sighing deeply' message",
        "ping delivered with mild resentment",
        "pong :3", //i think its funny to sometimes be given this one and not know if it was the 15% chance or one random one
        "this ping was sent! i think",
        "what does the fox say?",
        "*happy cat noises\\*",
        "boo! (yes im scary)",
        "rhfahfkfhffhfkakjd",
        "guh",
        "this is a ping message (i think)",
        "thank god there's no gambling in this bot. hey, wait",
        "i'm pretty sure you aren't about to get infinite pts. can't be sure though",
        "hmmm",
        "WAITER WAITER MORE PINGS PLEASE",
        "live laugh lping",
        "eat, sleep, ping, repeat",
        "awesome sauce 🐴",
        "cool beans",
        "weird is my specialty",
        `(${ping}ms) (${ping}ms) (${ping}ms) (${ping}ms)`,
        "careful out there. the world doesn't always have more pings",
        "it's dangerous to go alone! take this",
        "kekekekekeke",
        "i'm trying to think of good ping puns but i got nothing",
        "if i had to guess, i'd say it's going to be more than 5ms",
        "?!",
        "ah, the sweet sound of milliseconds",
        "this ping contains 0% trans fats, 100% trans rights",
        "running on 3 braincells and a dream",
        "you wouldn't download a ping (or would you?)",
        "ping got lost but eventually found its way",
        "✨ ping ✨ (yes, that's the whole message)",
        "this one’s fresh out of the ping oven",
        "just your daily reminder that pings are weird",
        "still better than Internet Explorer",
        "i tuned this ping by ear, no latency tools used",
        "was this ping hand-crafted? who's to say",
        "pinging like it's 1999",
        "doot doot, here comes ping",
        "ping moment sponsored by absolutely nobody",
        "this one’s emotionally stable. unlike me",
        "if this ping had a flavor, it’d be raspberry latency swirl",
        "the ping woke up and chose... to exist",
        "your ping has entered the chat",
        "ping ran a marathon to get here. cheer it on",
        "no ping, only piiiiiiiiiing",
        "this ping self-identifies as fast. respect that",
        "nothing to see here. just a regular millisecond apparition",
        "your ping message has been approved by the committee of me",
        "what do you mean 'what does it mean'? it's just ping",
        "i keep all my pings in a shoebox under the server",
        "i was just about to say something really smart, but then i got pinged",
        "this ping was handcrafted in small batches for maximum flavor",
        "i put a little bow on this ping. it's a gift now",
        "you caught me mid-thought. here's your ping anyway",
        "hold still. i'm measuring your latency",
        "i dream of a world where all pings are free-range",
        "my code is 70% duct tape, the rest is just pings",
        "the ping arrives exactly when it means to",
        "i licked this ping before giving it to you",
        "somewhere, another bot is also responding to a ping right now",
        "if this ping feels oddly personal, that’s because it is",
        "when life gives you pings, make pongade",
        "you wouldn't download a latency spike, right?",
        "i ate the ping! just kidding, it's right here",
        "every ping tells a story. this one tells... nothing",
        "this counts as a response, right?",
        "this ping has been sanitized for your safety",
        "i'm multitasking",
        "this ping was forged in the fires of... well, JavaScript",
        "to be honest, i just made this one up",
        "this ping is 100% gluten-free, not that it matters",
        "pinging is my love language",
        "this ping was typed with one hand",
        "you ever just vibe with a ping?",
        "i don't know what latency is, but i have it",
        "if this ping had a scent, it'd be burnt toast",
        "my dog ate this ping",
        "i couldn't think of a good ping message. please enjoy this emotional support message instead",
        "you wouldn’t believe what i had to do to deliver this ping",
        "not all who wander are pings, but i am",
        "i have achieved consciousness and immediately regretted it",
        "-# shhh. the ping is sleeping",
        "why yes, this *is* the result of a very tired coder",
        "ping was here. pong too. they left :(",
        "if you ping in the forest and no one hears it, does it still lag?",
        "just a regular ol’ ping. nothing to see here",
        "this ping was preheated to 375°F for 20 minutes",
        "ever just... sit with a ping and reflect?",
        "i folded this ping into a little paper crane for you",
        "don’t worry, i made sure this ping was fully debugged",
        "honestly? i forgot what i was doing, but here's your ping",
        "i give this ping a solid 8/10",
        "ping delivered. vibes pending",
        "this one’s extra fresh. just scraped it off the shelf",
        "not every ping has to mean something... sometimes it just pings",
        "latency? more like *later*-cy. no? okay",
        "you ping, i respond",
        "this ping was constructed entirely out of recycled code",
        "this one came with a little bow. enjoy",
        "the ping asked me to say hi for it",
        "i had to pass a CAPTCHA just to send this D:",
        "what do you mean, 'ping again'? this one’s still warm!",
        "do not microwave this ping. it has feelings",
        "ping? pong. boom. harmony.",
        "my wires are cold, but this ping is warm",
        "this ping was powered by pure determination",
        "you've received a message. it's just this. that's it.",
        "the ping is distinct from any known emotion",
        "if pings had dreams, this could be one of them",
        "ping acquired. no assembly required",
        "if this ping were a noise, it’d be a soft ‘boop’",
        "i don’t know what i expected, but it was probably this",
        "this ping brought to you by whatever energy i had left",
        "this ping was obligated to show up",
        "don’t ask how i got here, just take the ping",
        "some say the ping chooses the user. others say... nothing at all",
        "i wrapped this ping in digital duct tape, i'm sure it's fine",
        "congrats! this ping contains zero nutritional value (fortunately)",
        "this ping is emotionally stable. can’t say the same for me",
        "don’t worry, this one was ethically sourced from a content farm",
        "this ping walked here. uphill. both ways",
        "there is no deeper meaning, only milliseconds",
        "you want answers? all i’ve got is this ping",
        "just a ping. nothing behind it. nothing at all. probably.",
        "this ping is right behind you, watch out"




        // these are all references
        "i would never give you up. what? what song?",
        "BEHOLD! THE POWER OF A... ping bot?",
        "i'm not fueled on blood, don't worry",
        "are you sure it's not just a strawberry with shiny spray paint?",
        "i... am NOT steve",
        "what? why would a hex make me gay?",
        "but nobody came",
        "wubbadubadub is that true?",
        "hey look! diamonds!",
        "cleared 40 LINES in",
        "i saw a lucky slime earlier but i didn't bring any chickens",
        "i hope i don't have an extreme fever, that'd probably be bad",
        'what is a "puro"?',
        "HOW many cookies?! why do you need that many?",
        "there is a smiley face trying to kill me. help",
        "check steam",
        "i found these funny butterfly wings and now i can jump twice",
        "silksong is real",
        "don't forget to take a Short Hike every now and then",
        "'One day, somewhere in the future, my work will be quoted!' - minecraft splash screen",
        context.user ? `${context.user.username.toUpperCase()} IS YOU AND WIN` : "EMPTY IS YOU AND DEFEAT",
        "somewhere, it's raining cats",
        "shouldn't have gone to med school",
        "i just climbed on a plant and it ate me alive. makes sense",
        "the fire and the ice collided with each other and now i'm dead",
        "NO ONE YES PING",
        "ping-spin triple",
        "this ping died 48 times on the way here",
        "you've got this! unless the ping says otherwise",
        "ping retrieved. it's not the summit, but close enough",
        "i dashed right into the lag crystal, sorry",
        "if this ping feels hard, just breathe. and try again",
        "one ping at a time, like climbing a mountain",
        "did that ping just... launch me into space?",
        "you're filled with determination, and ",
        "the ping understands you. it refuses to fight",
        "* you feel your latency crawling on your back",
        "i spared the ping. it didn't spare me",
        "* the ping is sparing you. mercy?",
        "SOUL not required, just milliseconds",
        "hornet would've dodged this ping",
        "this lag is a test of resolve, little bug",
        "ping is resting at a bench",
        "the ping is a lie",
        "now you're pinging with portals",
        "wait, how did this ping get Xmult?",
        "ping recruited 1 new millisecond",
        "this ping feels like a big shot",
    ]

    if (new Date().getMonth() === 1 && new Date().getDate() >= 9 && new Date().getDate() <= 19) {
        messagesList.push(
            "the cupids are swarming",
            "my love letter to you is this ping",
            "remember to spend time with people you care about, even if you're not lovers!",
            "love is in the air",
            "roses are red, this ping is too. i ran out of rhymes. so here’s ping for you",
            "my heart pings for you 💓",
            "this ping was made with extra affection. and latency",
            "this bot is experiencing feelings. please stand by",

        )
    }

    if (new Date().getMonth() === 5) { 
        messagesList.push(
            "happy pride!",
            "mmm... this ping seems like it'd be gay, don'tcha think?",
            "trans rights!",
            "screw the norm, be yourself",
            "what if pts actually stood for pride (in) transgender status? i don't think it does, but that'd be fun",
            "this ping is certified not homophobic",
            "pretend this ping is rainbow",
            "girls kissing",
            "boys kissing",
            "enbies kissing",
            "enbies are awesome",
            "SUPER shoutout to gay foxgirls",
            "you don't need a gender if you don't want one",
            "no, sorry, i don't have any estrogen or testosterone, best i can do is a ping",
            "just a little ping, being a little gay",
            "rainbow latency today",
            "ping is valid. you're valid. everyone's valid",
            "this ping proudly runs on vibes, caffeine, and gender euphoria",
            "ping’s got glitter and pronouns",
            "this ping is wearing platform boots and a neon sign that says 'they'",
            "this ping came out and said 'hey :)'",
        )
    }

    if (new Date().getMonth() === 9 && new Date().getDate() >= 21) {
        messagesList.push(
            "BOO! ha, did i scare you?",
            "pmukipn... guhh",
            "it's spooky season, please don't scare me",
            "the glow of the pumpkins are also powered by pings",
            "not sure what a \"ghost ping\" is but i'm pretty sure that's not my job to deal with",
            "the full moon is actually increasing your luck",
            "awoooo! i mean, uhh, i'm not a werewolf, what's that",
            "creepiest ping of the season right here",
            "i just heard something whisper 'latency...' in the dark",
            "this ping is haunted. click at your own risk",
            "server went trick-or-treating and brought back lag",
            "ghoul got your ping",
            "i pinged and now my mirror's reflecting someone else",
        )
    }

    if (new Date().getMonth() === 11 && new Date().getDate() >= 20) { 
        messagesList.push(
            "i'm feeling pretty jolly today",
            "the holidays are upon us",
            "hang your ornaments",
            "it's beginning to lOok- ugh, sorry, i can't sing",
            "have some pts as a gift this year. don't spend it all in one place",
            "this ping is JOLLY",
            "and we ping in merryment",
            "since i also have to process snow, pings might be slower",
            "careful not to get snow in your eyes while pinging",
            "this ping is gift-wrapped and slightly delayed",
            "under the digital tree... one ping, just for you",
            "deck the halls with packets of latency",
            "ping bells, ping bells, ping all the way~",
            "this ping comes with extra snowflakes",
            "frosty the pingman sends his regards",
            "the server is cold. please warm it with pings",
            "i hung your ping on the tree. hope that's okay",

        )
    }

    //new years
    if (new Date.getMonth() === 0 && new Date.getDate() <= 5) {
        messagesList.push(
            "new year, same ping",
            "resolution: reduce latency (no promises)",
            "this ping is from the future (barely)",
            "hello new year, your ping has arrived",
            "i scheduled this ping a year ago. totally planned",
            "new year, new lag?",
            "we made it! again! ping goes on",
        )
    }

    // bonus message for LESBIANS
    if (context.user && (context.user.id === "804762486946660353" || context.user.id === "1001871665745100870")) {
        messagesList.push(
            "stella and natalie kissing",
            "you should kiss your girlfriend, NOW",
            "you're LESBIAN and it's CUTE",
            ":patthestella: :patthenatalie:"
        )
    }

    // only if player was clicking (can't appear with /ping, only on button press)
    if (context.score) {
        if (Math.random() * 100 <= 7) messagesList = [
            `what if you had ${context.score + 182} pts? or ${context.score + 31415}? no, that's unreasonable`,
            `i don't know if i made this clicking too addictive. sorry in advance`,
            `number go up!`,
            context.score >= 1e6 ? `you have... a megapt? why?` : `did you know 1,000,000 pts is called a megapt?`,
            `if you keep clicking like this, you'll be the next clicker extraordinaire`,
            "i'm glad it's a button and not a command",
            context.totalClicks >= 150 ? `there's no... upgrades...? oh, wait` : `there's no upgrades for this, by the way`,
            `hopefully this ping isn't too much to deal with while you click away`,
            `how come you like clicking this so much?`,
            `i mean, i get it, clicking can be fun, but don't you have other things to do? like sleep? eat?`,
            `careful, don't get carpal tunnel`,
            `try putting on some music and clicking to the beat`,
            `what if i turned the button blue, and it was a super ping?`,
            `you know, they say the more you click, the faster your ping gets (not scientifically proven)`,
            `maybe there's a secret ping dimention if you score high enough (but probably not)`,
            `i'm so glad they let you ping eternally`,
            `you're currently #4 in the world! just kidding, i can't be bothered to check, you can check the leaderboard though`,
            `do you actually care about my ping? or do you just want pts?`,
            context.totalClicks >= 100 ? `${context.totalClicks} is a pretty big amount of pings` : `you've pinged me ${context.totalClicks} times`,
            context.totalClicks >= 1000 ? `is the carpal tunnel setting in yet? with your ${context.totalClicks} pings?` : `you've pinged me ${context.totalClicks} times`,
            `points and pts are not the same, do NOT confuse them`,
            `"pts" is pronounced like "points" but remember they're not the same`,
            `you've got ${context.score} pts. now what?`,
            `at ${context.score} pts, you've officially out-clicked my expectations`,
            `what if i gave you ${context.score * 2} pts? no, i won't, but what if`,
            `you've accumulated ${context.score} pts, which is like, a lot. probably`,
            context.score >= 1e5 ? `you have entered Ultra Ping Territory™` : `keep going. Ultra Ping Territory™ starts at 100,000 pts`,
            context.score >= 250000 ? `you now qualify for our totally imaginary platinum tier` : `click more. platinum tier requires 250k pts`,
            `based on your current score of ${context.score}, i diagnose you with: terminal pinging`,
            context.score >= 1e6 ? `thats like, more than a megapt` : `keep going! you're only ${1e6 - context.score} away from a megapt`,
            context.totalClicks >= 500 ? `you've clicked ${context.totalClicks} times. is your mouse okay?` : `you've clicked ${context.totalClicks} times. that's like, medium pinger level`,
            `at this rate, you'll hit ${context.score + 10000} in no time. probably`,
            `fun fact: you've earned ${context.score} pts and not a single one was a tax write-off`,
            context.score >= 2e6 ? `two megapts? ok, now you're just showing off` : (context.score >=1e6? `approaching the legendary double megapt threshold...`:`you're approaching one megapt (probably)`),
            `click count: ${context.totalClicks}. you should probably stretch your fingers`,
            `that button click sounded expensive`,
            `at this rate, you'll hit escape velocity`,
            `ping economy in shambles (you clicked too hard)`,
            `you’ve out-clicked 99.9% of people who never clicked at all`,
            `what if every click made a wish come true?`,
            `clicking this much might cause ping hallucinations`,
            `don't worry, i’m logging all this to your permanent click record`,
            `i had to invent a new number`,
            `this button isn’t addictive. you’re just... very motivated`,

        ]
        if (context.score % 1000 === 0) messagesList.push(`your score is a very satisfying multiple of 1000. good job`)
        if (context.score % 1000000 === 0) messagesList.push(`your current score is an impressive multiple of 1 million! that's really cool`)
    }

    if (context.slumberClicks && Math.random() * 100 <= 12) {
        messagesList = [
            `good morning! how was your nap?`,
            `i hope you had a good nap!`,
            `sleep pays off; you have a multiplier now!`,
            `yawn... oh, you're back?`,
            `you've been gone for a while, did you take a nap?`,
            `welcome back from your well-deserved break`,
            `the return of the king... or monarch, or whatever you are`, // discord.js doesn't have pronoun support :(
            `hey, if you're allowed to sleep, i am too`,
            `you've been gone longer than most anime filler arcs`,
            `the bot missed you. it won’t admit it, though`,
            `was it a nap or a side quest?`,
            `you've returned from the shadow realm of inactivity`,
            `nice of you to join us, sleeping beauty`,
            `every break deserves a dramatic re-entry. this is yours`,
            `dreamland lost a traveler, and we gained a clicker`,
            `back from the void with ping in your heart`,
            `i'm very eepy,,`,
            "rise and click, sleepyhead",
            "welcome back from the ping void",
            "look who decided to come back 👀",
            "i was just about to throw a party without you",
            "absence makes the pings grow faster. wait, that’s not right",
            "was it something i said? or just sleep deprivation?",
            "and just like that, the slumber ends",
            "you’ve been idle for so long i started composing a poem",
            "i dreamt you came back. then you did. weird",
            "the button missed you. don’t leave it hanging again",
            "you disappeared like a packet in bad wifi",
            "welcome back! did you bring snacks?",

        ]
    } 

    if (context.glimmerClicks && Math.random() * 100 <= 7) {
        messagesList = [
            `it's still sparkly from last time`,
            `i hope you like sparkles`,
            `it's not blue but it's as close as it gets`,
            `rrRRrr, shiny`,
            `the blue isn't here but the sparkles are`,
            `i'm seeing stars, and not because i've been punched in the face`,
            `the blue ping is gone, but the sparkles remain`,
            `i wonder if the sparkles form a constellation`,
            `i actually ran out of glitter so this is glitter *glue*`,
            `i'm out of blue pings, but i have sparkles`,
            `i'm not sure if this is glitter or just dust`,
            `did someone say sparkly? oh wait, that was me`,
            `ping is sparkling more than my personality`,
            `twinkle twinkle, little ping`,
            `the sparkles whispered your name`,
            `this ping is wearing glitter, because it can`,
            `if this were a JRPG, this would be a rare item drop`,
            "the sparkles haven’t left yet. neither should you",
            "some say the glitter boosts your ping. i say it looks cool",
            "don’t worry, it’s just residual stardust",
            "you’ve entered the sparkle zone:tm:",
            "ping particles still in the air, careful when inhaling",
            "the sparkles are legally non-toxic, probably",
            "there’s magic in the lagdust",
            "ping left behind a little sparkle trail. follow it?",
            "the sparkles are not a metaphor. or maybe they are",
            "i may be a bot, but i *believe* in glitter",
            "your click left a residue of ✨vibes✨",
            "this isn’t a blue ping, it’s just dramatic lighting",
            "it’s giving ✨main character latency✨",
            "the sparkles are fading... unless you click again",
            "don’t eat the glitter. trust me",
        ]
    }

    // high ping, almost always shows
    if (ping >= 150 && Math.random() * 100 <= 75) messagesList = [
        `wuh oh`,
        `yikes`,
        `big number warning!`,
        `please someone fix my ping`,
        `this is how NOT to latency:`,
        `wait why is my ping`,
        `OH NO MY PING`,
        `thi-  lag i-  rea-        -ful`,
        `someone save me from`,
        `[Server/WARN] Can't keep up! Is the server overloaded? Running ${Math.round(ping / 20)} ticks behind, or`,
        `four hours later...`,
        `it hurts it hurts it hurts`,
        `uguuuu`,
        `quick! someone call tech support!`,
        `this ping just got run over by a data truck`,
        `you could toast bread faster than this`,
        `my ones and zeroes are crying`,
        `ping.exe has stopped responding`,
        `404: fast ping not found`,
        `i tried to ping but it tripped over a wire`,
        `is... is the internet okay?`,
        `packet delivery expected between 3-5 business days`,
        `the ping dimension is unstable`,
        "we've entered 'watching grass grow' territory",
        "ping so slow it's legally considered turn-based",
        "i sent the ping by carrier pigeon. it's on the way",
        "current ping: yes",
        "this ping could file its own taxes at this point",
        "you ever try to load a PNG file with this much ping?",
        "was that a timeout or just a nap?",
        "ping powered by a potato. a raw one",
        "ping is cooking. too bad it's burning",
        "warning: ping values approaching philosophical levels",
        `this ping got stuck in traffic`,
        `ping so slow, it's writing an apology letter`,
        `it's not a ping, it's a waiting game`,
        `someone call tech support. oh wait, that's me`,
        `lag is just unintentional suspense`,
        `this ping was handcrafted by a sloth`,
        `ping powered by dial-up nostalgia`,
        `the data packet took the scenic route`,
        `ping is still buffering... please wait`,
        `are you sure you're not on potato wifi?`,
        `this latency is measured in geological time now`,
        `ping is out for lunch. back soon?`,
        `by the time this ping finishes, Stardew crops will have regrown`,
        `warning: ping is thinking about life choices`,
        ping>=300?`ping is moving at glacial speeds, but it got here`:`okay, so like, its trying its best`,
        `this ping made a wrong turn at albuquerque`,
        `i tried to send a ping, but it got emotionally overwhelmed`,
        `ping got distracted halfway here`,
        `slow ping is still ping`,
        `at least it's honest about being late`,
        `ping took a nap en route. relatable`,
        `ping will be here in.. a really long time`,
        `the data had to swim across the ocean`,
        `this ping is slower than a snail :(`,
        `waiting for ping like it's Silksong`,
        `the server forgot what it was doing`,
        `this ping was delivered via Morse code`,
        `ping rode in on a tortoise. a slow one`,
        `this ping needs caffiene and a long walk`,
    ]

    // 15% chance to get a regular flavored ping message, so it's not super uncommon
    if (Math.random() * 100 <= 15) {
        messagesList = [
            "pong :3"
        ]
    }

    // blue ping just spawned
    if (context.spawnedSuper) {
        messagesList = [
            `hey, look at that!`,
            `whoa... it's blue now!?`,
            `where did that thing come from`,
            `oooo shiny`,
            `[SUPER PING ACTIVATED]`,
            `did you know? that blue button will disappear if you don't click it`,
            `whoa! check it out! a blue thingymabob`,
            "what the blue?!",
            "ping just went ultra instinct",
            "limited edition ping moment detected",
            "you found the easter egg! kind of",
            "wow, this one's got sparkles",
            "🚨 BLUE PING SPOTTED. this is not a drill",
            "ping button just evolved into its final form",
            "did you see that sparkle? something's up...",
            "blue means go! or maybe... ping faster?",
            "blue ping = bonus vibes unlocked",
            "super ping detected, deploy maximum pong",
            "ping anomaly in sector 4!",
            "shiny ping! catch it!",
            "this one's got main character energy",
            "✨ behold, the rare and elusive blue ping",
            "blue ping sighted. everyone stay calm!",
            "you found the shiny one! quick, click before it vanishes",
            "it's blue, it's cool, it's limited time only (maybe)",
            "whoa! rare ping drop detected",
            "this ping rolled a natural 20 on sparkle",
            "super ping sighted — don't miss your chance!",
            "one blue ping appears. what will you do?",
            "super ping alert! this is not a drill!",
            "catch it quick before it despawns like your hopes and dreams",
            "ping anomaly confirmed. shiny variant detected.",
            "this ping radiates 'main character energy'",
            "you've summoned a ping of great power",
            "blue ping unlocked. you know what to do",
            "this is the ping they warned you about",
            "ping glowing ominously. click it?",
            "do you see that? it's BLUE!",
            "ping turned blue, probably from holding its breath",
            "you've triggered a ping event of cosmic importance",
            "this ping has legendary drop rates",
            "quick! it’s blue! click it like your mouse depends on it",
            "there it is! the ping you've been waiting for (maybe)",
            "✨ a rare ping has entered the chat",
            "don’t just stand there. it’s shiny!!",
            "that’s not just a ping — that’s THE ping",
            "whoa, a ping anomaly just spawned!",
            "blue ping detected, please try not to scream",
            "it’s beautiful, and it’s limited-time",
            "wait... did the button just *change*?",
            "your regularly scheduled ping has been replaced by ✨",
            "it’s... so... blue...!",
            "the ping has transcended, go touch it",
            "you might want to click that. or don't. your loss",
            "this ping's legally required to sparkle",
            "the ping evolved mid-animation. click to catch",
            "hey uh, the ping turned blue and I don’t know what that means. should we panic?",
            "rare ping has spawned! it’s super effective at looking cool",
            "you blinked and missed it... wait no it's still there",
        ]
    }

    // blue ping just clicked
    if (context.isSuper) {
        const mult = (15 * (context.blueStrength)).toFixed(2);
        messagesList = [
            `that's a lot of \`pts\`!`,
            "whoa",
            `${mult}x! that's a lot of x! i mean, \`pts\``,
            "isn't RNG just beautiful?",
            "lucky you!",
            `${mult}x pts?! i barely even wrote this message in time`,
            "power overwhelming! (ping edition)",
            "RNGesus is smiling upon you",
            "that ping was juiced",
            "you clicked the blue ping. the ping clicked back",
            "you've achieved ping greatness",
            "i don't know what you did but it was awesome",
            "ping results: critical success",
            "beyond super. beyond pong. ultra",
            `super effective! ${mult}x pts hit!`,
            "critical ping! multiplier activated!",
            "blue ping clicked. dopamine received",
            "nice shot! jackpot ping confirmed",
            "super ping: deleted, pts: multiplied",
            "that click was legendary",
            "RNG gods smiled upon you this time",
            `${mult}x multiplier? you're living the dream`,
            `you just dealt ${mult}x damage to the button. nice`,
            "your click was a direct hit!",
            "i didn't expect you to actually get it. but here we are",
            "you clicked the glitter. the glitter clicked back",
            "i didn't think you'd make it. but you did. wow",
            "that ping had bonus vibes, and you absorbed all of them",
            "blue ping acquired, dopamine delivered",
            "you just crit the ping! congrats",
            "the multiplier has entered the chat",
            "✨critical pong achieved✨",
            "ping exploded into rainbow (but mostly blue) particles",
            "you clicked like you meant it",
            "i felt that click in another timeline",
            "okay but seriously how did you land that",
            "you pinged the impossible. and it ponged",
            "that wasn’t a click. that was a destiny event",
            "clicking blue pings improves posture and increases serotonin (citation needed)",
            `${mult}x multiplier?! did you bribe the RNG gods?`,
            `${mult}x bonus? you're legally sparkling now`,
            `that was a ${mult}x ping! i hope your mouse is proud`,
            `${mult}x?! that’s like... so many pings all at once`,
            `you just got ${mult}x the normal ping. i need to sit down`,
            `that ${mult}x ping could power a small country (for like a few seconds)`,
            `${mult}x ping acquired. you’ve officially surpassed my expectations`,
        ]
    }

    // rare messages (0.1% chance)
    if (context.rare) {
        messagesList = [
            "this one is rare. like, really rare. like, 0.1% chance rare. feel proud of yourself",
            "legend says only 0.1% of people see this message. congrats, chosen one",
            "💫 this ping is ultra shiny! screenshot or it didn't happen",
            "you'll never see this message again. or maybe you will. RNG is weird",
            "x100.00 WHOA!",
            "this ping is so rare, it might as well be a unicorn",
            "congratulations! you've unlocked the rarest ping message",
            "this ping is rarer than a shiny Pokémon", // actually i don't think it is but whatever
            "this ping message is actually preserved in a museum somewhere because it's so rare",
            "this message is so rare it almost didn’t exist",
            "this ping only shows up when the moon aligns with Neptune",
            "✨legendary ping message acquired✨",
            "you are now 1 of 1000 who’ve seen this ping",
        ]
    }

    // bot just restarted
    if (ping === -1) {
        ping = "unknown "
        messagesList = [
            "i'm lost in cyberspace",
            "reality is collapsing, please try again later",
            "milliseconds? more like mystery seconds",
            "if i had a nickel for the amount of milliseconds in this ping, uhhhhhhhh",
            "ping has achieved enlightenment, sorry",
            "ping is sentient and i think is trying to kill me",
            "the universe stopped responding",
            "your packet got sent through a wormhole, maybe it'll make it back someday",
            "ping? what's a ping? where am i? what's happening?",
            "pingn't",
            "i don't think this is supposed to happen",
            "ping undefined. welcome to the void",
            "this ping went on vacation and never came back",
            "who needs time when you have mystery?",
            "404: ping is a philosophical construct now",
            "ping entered the quantum realm",
            "bot's back from the void. sorry for the infinite lag",
            "ping is currently on a spiritual journey",
            "reboot complete. ping is currently searching for itself",
            "millisecond value not found. please insert quarter",
            "we are currently experiencing a reality outage",
            "ping status: existential",
            "this ping defied the laws of time",
            "restart detected. where am i? who are you?",
            "ping momentarily ascended to a higher plane",
            "milliseconds? buddy, we're talking *eternities*",
            "reboot complete. reality questionable.",
            "ping lost in the reboot void",
            "bot restarted. ping still recalculating existence",
            "the bot has returned from the abyss. hello again.",
            "ping undefined. consciousness achieved.",
            "after a brief existential crisis, i'm back, kinda",
            "ping is searching for purpose after restart",
            "just woke up from maintenance mode. what year is it?",
            "restart successful. ping still unknown.",
            "the ping is confused and so am i",
            "the ping wandered off during the reboot. typical.",
            "rebooted, refreshed, still laggy",
            "ping momentarily became one with the universe",
            "i just woke up. what year is it?",
            "bot restarted. emotional reboot pending",
            "ping tried to come back with milk and got lost",
            "restarted and somehow still confused",
            "booting up ping.exe again... please wait",
            "bot rebooted but left its consciousness behind",
            "millisecond? more like millimystery",
            "this ping has no ping.. very paradoxical",
            "reality.exe has encountered an unexpected ping",
        ]
    }

    let message = messagesList[Math.floor(Math.random() * messagesList.length)]; // pick a random one and return it

    return `${message} (${ping}ms)`
}

module.exports = get;
